<a href="https://colab.research.google.com/github/viett887g/numpy2/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import math
import random

In [ ]:
1 Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5

, giá trị các phần tử của ma trận được

sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
vecA= []
for i in range(5):
  acid=[]
  for j in range(7):
    acid.append(rd.randint(1,199))
  vecA.append(acid)

print(np.array(vecA))

[[ 96 122  37 178 152 164 179]
 [124 190 123  99  16 120  51]
 [ 93  15 146 142  58  41 155]
 [ 48  59  98 128  18 179  99]
 [115 137  85  36  78  28 181]]


In [ ]:
2Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [ ]:
np_vec = np.zeros((6,7))
print(np_vec)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
3 Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ R7×7

, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả

xuất ra màn hình.

In [ ]:
vecB = []
for i in range(7):
  heli=[]
  for j in range(7):
    heli.append(rd.randint(1,199))
  vecB.append(heli)

print(np.array(vecB))

[[131 157  86  76   5  86 134]
 [126  70  53 174  37  27 122]
 [130  47 161 167 142  71  78]
 [ 48  67 112  80  37  57 168]
 [ 11 194 188  17 152  66  57]
 [  6 133 110 188  73 123   1]
 [ 51  82  35  16 104  40  24]]


In [ ]:
4Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.

In [ ]:
vecC=np.diag([1,2,3])
print(vecC)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
5 Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.

In [ ]:
vecD = []
for i in range(5):
  clo=[]
  for j in range(7):
    clo.append(rd.randint(1,199))
  vecD.append(clo)

print(np.array(vecD))
vecD= np.triu((vecD))
print(vecD)


[[122  83  19 121 175  94 125]
 [105 153 163 145  87 129 122]
 [131  97 104 194 174 197  14]
 [ 50  10 189 137 149 114  29]
 [ 77 141 181  30  50   8 111]]
[[122  83  19 121 175  94 125]
 [  0 153 163 145  87 129 122]
 [  0   0 104 194 174 197  14]
 [  0   0   0 137 149 114  29]
 [  0   0   0   0  50   8 111]]


In [ ]:
6 ma tran tam giac duoi

In [ ]:
vecD = []
for i in range(5):
  clo=[]
  for j in range(7):
    clo.append(rd.randint(1,199))
  vecD.append(clo)

print(np.array(vecD))
vecD= np.tril((vecD))
print(vecD)

[[ 60 120  65  32  12 150 131]
 [ 49   5 164 143 122 184 163]
 [  5  64  95  14  99 101 144]
 [ 17  74 177 167 102  29  27]
 [196 199  61 131  18  12 166]]
[[ 60   0   0   0   0   0   0]
 [ 49   5   0   0   0   0   0]
 [  5  64  95   0   0   0   0]
 [ 17  74 177 167   0   0   0]
 [196 199  61 131  18   0   0]]


In [ ]:
7Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [ ]:
vecF=np.eye((3))
print(vecF)
vecF=np.identity(9)
print(vecF)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
8 Phép cộng ma trận: Am×n + Bm×n = Cm×n. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

In [7]:
vecG= []
for i in range(6):
  mage= []
  for i in range(7):
    mage.append(rd.randint(1,20))
  vecG.append(mage)
vecG = np.array(vecG)
print("vecG=n\ ", vecG)

vecH= []
for i in range(6):
  oxi=[]
  for i in range(7):
    oxi.append(rd.randint(1,15))
  vecH.append(oxi)
print(np.array(vecG))
       


vecG=n\  [[12 14  2  5 20  8  3]
 [ 1 17  2 18 13 14 16]
 [ 5  5 13 15 12 13 14]
 [ 1  7 18  4 14 11 14]
 [ 5 20 10 12 20 15  6]
 [ 5 11 16  9  2 13 11]]
[[12 14  2  5 20  8  3]
 [ 1 17  2 18 13 14 16]
 [ 5  5 13 15 12 13 14]
 [ 1  7 18  4 14 11 14]
 [ 5 20 10 12 20 15  6]
 [ 5 11 16  9  2 13 11]]


In [8]:
A=vecG+vecH
print(A)

[[16 21  7 20 23 21 13]
 [ 3 27 10 33 14 25 20]
 [ 9 10 18 23 24 22 22]
 [ 8 22 32 17 22 14 27]
 [10 33 23 15 25 28 10]
 [ 9 16 30 16  5 18 20]]


In [ ]:
Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

In [52]:
vecj= []
for i in range(3):
  natri= []
  for i in range(7):
    natri.append(rd.randint(1,20))
  vecj.append(natri)
vecj = np.array(vecj)
print("vecj=n\ ", vecj)

vecj=n\  [[14 19  6  2 13 10 20]
 [ 7  1  8 15 12  5 20]
 [10 11  1 15  8  5 11]]


In [53]:
print(vecj.T)

[[14  7 10]
 [19  1 11]
 [ 6  8  1]
 [ 2 15 15]
 [13 12  8]
 [10  5  5]
 [20 20 11]]


In [ ]:
Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()

In [54]:
veck= []
for i in range(5):
  bari= []
  for i in range(7):
    bari.append(rd.randint(1,20))
  veck.append(bari)
veck = np.array(veck)
print("veckveck=n\ ", veck)

vecl= []
for i in range(7):
  canxi= []
  for i in range(3):
    canxi.append(rd.randint(1,20))
  vecl.append(canxi)
vecl = np.array(vecl)
print("veclvecl=n\ ", vecl)


veckveck=n\  [[ 4 19 12 11  1 11  6]
 [ 7 17 11  5  2  1 17]
 [ 9  5 17  3  6  1 12]
 [15  8  5  6  8  8 11]
 [17 16 17  4 15 12 17]]
veclvecl=n\  [[19 14  8]
 [18 19  4]
 [ 7 13  6]
 [15 19 19]
 [17 16 13]
 [14 15 15]
 [17  2 16]]


In [55]:
print(veck.dot(vecl))

[[ 940  975  663]
 [ 928  740  598]
 [ 745  634  536]
 [ 989  811  696]
 [1502 1293 1025]]


In [ ]:
Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi

ý: sử dụng hàm numpy.linalg.inv()

In [ ]:
9Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.

In [57]:
vecz= []
for i in range(1):
  kali= []
  for i in range(8):
    kali.append(rd.randint(1,20))
  vecz.append(kali)
vecz = np.array(vecz)
print("vecz=n\ ", vecz)

vecz=n\  [[ 6  1 18 16  6  5  8  6]]


In [ ]:
Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [59]:
vecz= []
for i in range(8):
  kali= []
  for i in range(1):
    kali.append(rd.randint(1,20))
  vecz.append(kali)
vecz = np.array(vecz)
print("vecz=n\ ", vecz)

vecz=n\  [[18]
 [13]
 [19]
 [ 7]
 [ 5]
 [13]
 [ 5]
 [14]]
